# 起動時に通知するチャンネルのID
CHANNEL_CALL_ID: '632987047350501377'

# vcのログを出力するチャンネルのID
VC_LOG_CHANNEL: '632817156022730782'

# サルモネラ菌のサーバーID
SALMONELLA_ID: '627929230331740177'

# べろばあのサーバーID
BEROBA_ID: '714020537231343653'

# コマンドが入力できるチャンネル
VC_CHANNEL:
  ID: '811981203435421708'
  MESSAGE: '811981710656667678'

# AFK用のチャンネル
AFK_CHANNEL:
  - AFK
  - 宿屋
  - 寝落ちしています。

# DevModeに切り替えられるロール
DEVELOP_ROLE:
  - ヤバイわよ！

# 画面共有しているか判別するロール
STREAMING_ROLE: '785179265284964383'
# カメラが動いているか判別するロール
VIDEO_ROLE: '788673883933769738'
# スピーカーミュートしているか判別するロール
DEAF_ROLE: '788701105739268099'
# 中華のロール
CHINA_ROLE: '809095677153640489'

# ホワイトリストのシート名とセルの範囲
WHITE_LIST:
  SHEET: ホワイトリスト
  CELLS: A2:A100

# APIのURL
API_URL:
  # ひらがな化APIのURL
  HIRAGANA: 'https://labs.goo.ne.jp/api/hiragana'
  # gttsのURl
  GTTS: 'https://translate.google.com'

# 音源のURL
URL:
  YABAI: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fyabai.wav?alt=media&token=2822b79e-3a96-4ba1-b41b-faf08c8dc83a
  YABAIWAYO: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fyabaiwayo.wav?alt=media&token=2e605577-37c6-4abc-99f0-f8cfd8aca9ad
  YABAIDESU: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fyabaidesune.wav?alt=media&token=f8b00f56-e73a-4453-9e46-3ac85e61d8fb
  YABAIYABA: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fyabayaba.wav?alt=media&token=8e35e529-fefe-47b1-8181-e0774e95b2dc
  YABAIFULL: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fyabaiwayofull.wav?alt=media&token=c9391090-865b-425e-8a1d-6aecde7e7cfa
  YABAIYABAI: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fyabayabai.wav?alt=media&token=da346b8f-d11d-4a2e-b5e8-64ea297cd789
  YABAISLOW: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fyabaislow.wav?alt=media&token=13ab1306-a81d-426f-8410-d04403416268
  YABAIOTWR: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fyabaiotwr.wav?alt=media&token=a9b46699-ff50-4f1c-b02f-2055ea1a0b8d
  JINNAI: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fjinnai.wav?alt=media&token=39fa812f-1154-4643-9d91-0b4fc16353ad
  JINNAITOMONORI: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fjinnaitomonori.wav?alt=media&token=95e61e67-ce7d-4b54-90a2-2f7ac28088a1
  HIKAKIN: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fhikakin.wav?alt=media&token=a0a00909-8030-4ef9-ac0b-e76fd1ed59ee
  HELLOYOUTUBE: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2FhelloYouTube.wav?alt=media&token=1f789380-a758-4af4-9fe8-1b48443a061e
  HIKAKINTV: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fhikakintv.wav?alt=media&token=ade50593-2da3-4788-a306-d89c22e3fa09
  SETOKOUJI: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fsetokouji.wav?alt=media&token=8519fab6-7ca9-43c1-8ccf-cf832a67ce84
  MISUZU: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fmisuzu.wav?alt=media&token=3eee9f2f-f82f-45e6-973f-234f7134cf42
  SUSHIRO: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fsushiro.wav?alt=media&token=7a960e18-4055-4cba-8f05-a060956b37c0
  USAMARU: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fusamaru.wav?alt=media&token=eabc4d55-f604-47b8-8841-8f0d56544342
  NYARU: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fnyaru.wav?alt=media&token=6e6c9ca1-9b34-49c0-aeeb-076290041cbc
  HEERO: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fheero.wav?alt=media&token=ca8a6f46-28b0-4f77-9f5a-660c1de3605a
  DEDEN: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fdeden.wav?alt=media&token=72bb55d3-63bf-4629-8122-bedc0d884522
  GI: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fgi.wav?alt=media&token=6c2e1624-40e5-4fe2-a68a-701e3b629729
  FUNAKOSHI: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Ffunakoshi.wav?alt=media&token=658f2afd-61f0-469c-a142-eb5e1f167e58
  KATAHIRA: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fkatahira.wav?alt=media&token=ade1ac50-5efe-43f2-9f6d-c5a9900d4490
  REITYAN: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Freityan.wav?alt=media&token=1bdccd28-177c-4a78-af71-6f348eaa119f
  KARIN: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fkarin.wav?alt=media&token=7dd1a5ca-c9a6-4701-9154-df5640d25afc
  ZAWAZAWA: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fzawazawa.wav?alt=media&token=5e2568ff-5522-404c-858f-ff2331a35ef1
  MUSCLE: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fmuscle.wav?alt=media&token=dec0ade7-8c9e-4f5c-a485-1e99443b7e39
  NEKO: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2Fneko.wav?alt=media&token=47fda8c8-0c8b-4679-8ce4-029f242eac81
