# 起動時に通知するチャンネルのID
CHANNEL_CALL_ID: '632987047350501377'

# リモートヤバイわよ！するチャンネルのID
REMOTE_YABAI_CHANNEL: '627929231397224509'

# コマンドが入力できるチャンネル
COMMAND_CHANNEL:
  - 効果音
  - 効果音-001
  - テスト用
  - bot-test
  - vc用

# AFK用のチャンネル
AFK_CHANNEL:
  - AFK
  - 宿屋

# DevModeに切り替えられるロール
DEVELOP_ROLE:
  - ヤバイわよ！

# リモートヤバイわよ！できるロール
REMOTE_YABAI:
  - ヤバイわよ！

# ホワイトリストのシート名とセルの範囲
WHITE_LIST:
  SHEET: ホワイトリスト
  CELLS: A2:A100

# 音源のURL
URL:
  YABAI:      https://nextcloud.salmonella.tk/index.php/s/2MwnkFwQGiQGMRR/download
  YABAIWAYO:  https://nextcloud.salmonella.tk/index.php/s/b979bn3pGAiczY3/download
  YABAIDESU:  https://nextcloud.salmonella.tk/index.php/s/8wKm4tijSKm8ag3/download
  YABAIYABA:  https://nextcloud.salmonella.tk/index.php/s/ZdGwzSBefcGno2b/download
  YABAIFULL:  https://nextcloud.salmonella.tk/index.php/s/Q3NzaWm4NpmnpSn/download
  YABAIYABAI: https://nextcloud.salmonella.tk/index.php/s/y3zAwdRYiDmMmdr/download
  YABAISLOW:  https://nextcloud.salmonella.tk/index.php/s/pSbrEafTGQryfP9/download
  YABAIOTWR:  https://nextcloud.salmonella.tk/index.php/s/6zwRmgCAHm29Gzn/download
