# 音声のURL
URL:
  BASE: https://firebasestorage.googleapis.com/v0/b/practice-smicle.appspot.com/o/cal-bot%2
  YABAI: Fyabai.wav?alt=media&token=2822b79e-3a96-4ba1-b41b-faf08c8dc83a
  YABAIWAYO: Fyabaiwayo.wav?alt=media&token=2e605577-37c6-4abc-99f0-f8cfd8aca9ad
  YABAIDESU: Fyabaidesune.wav?alt=media&token=f8b00f56-e73a-4453-9e46-3ac85e61d8fb
  YABAIYABA: Fyabayaba.wav?alt=media&token=8e35e529-fefe-47b1-8181-e0774e95b2dc
  YABAIFULL: Fyabaiwayofull.wav?alt=media&token=c9391090-865b-425e-8a1d-6aecde7e7cfa
  YABAIYABAI: Fyabayabai.wav?alt=media&token=da346b8f-d11d-4a2e-b5e8-64ea297cd789
  YABAISLOW: Fyabaislow.wav?alt=media&token=13ab1306-a81d-426f-8410-d04403416268
  YABAIOTWR: Fyabaiotwr.wav?alt=media&token=a9b46699-ff50-4f1c-b02f-2055ea1a0b8d
  JINNAI: Fjinnai.wav?alt=media&token=39fa812f-1154-4643-9d91-0b4fc16353ad
  JINNAITOMONORI: Fjinnaitomonori.wav?alt=media&token=95e61e67-ce7d-4b54-90a2-2f7ac28088a1
  REVOLUTION: Frevolution.wav?alt=media&token=22e8552b-b4ce-49d1-ae10-0d56913ce4b9
  REVO_LUTION: Frevo_lution.wav?alt=media&token=f938ebc0-b86d-4d74-9f3c-a8b3aac4de1d
  NANDEDARO: Fnandedaro.wav?alt=media&token=6a53d107-00d0-4807-89cc-55e749693823
  HIKAKIN: Fhikakin.wav?alt=media&token=a0a00909-8030-4ef9-ac0b-e76fd1ed59ee
  HELLOYOUTUBE: FhelloYouTube.wav?alt=media&token=1f789380-a758-4af4-9fe8-1b48443a061e
  HIKAKINTV: Fhikakintv.wav?alt=media&token=ade50593-2da3-4788-a306-d89c22e3fa09
  SEIKIN: FSEIKIN.wav?alt=media&token=ee8e1bcb-f09f-4087-8503-e94d224d5d84
  SETOKOUJI: Fsetokouji.wav?alt=media&token=8519fab6-7ca9-43c1-8ccf-cf832a67ce84
  MISUZU: Fmisuzu.wav?alt=media&token=3eee9f2f-f82f-45e6-973f-234f7134cf42
  SUSHIRO: Fsushiro.wav?alt=media&token=7a960e18-4055-4cba-8f05-a060956b37c0
  RAKUTEN_MOBILE: Frakuten_mobile.wav?alt=media&token=19617ccc-6d1d-4a27-b79e-b9aed43314a1
  FBI: Ffbi.wav?alt=media&token=4367a1a8-271e-49b4-a347-902079fe3d92
  USAMARU: Fusamaru.wav?alt=media&token=eabc4d55-f604-47b8-8841-8f0d56544342
  NYARU: Fnyaru.wav?alt=media&token=6e6c9ca1-9b34-49c0-aeeb-076290041cbc
  BASILISK: Fbasilisk.wav?alt=media&token=f7f561c8-37bf-4c6a-a605-ecb87549c908
  HEERO: Fheero.wav?alt=media&token=ca8a6f46-28b0-4f77-9f5a-660c1de3605a
  DEDEN: Fdeden.wav?alt=media&token=72bb55d3-63bf-4629-8122-bedc0d884522
  GI: Fgi.wav?alt=media&token=6c2e1624-40e5-4fe2-a68a-701e3b629729
  FUNAKOSHI: Ffunakoshi.wav?alt=media&token=658f2afd-61f0-469c-a142-eb5e1f167e58
  KATAHIRA: Fkatahira.wav?alt=media&token=ade1ac50-5efe-43f2-9f6d-c5a9900d4490
  REITYAN: Freityan.wav?alt=media&token=1bdccd28-177c-4a78-af71-6f348eaa119f
  KARIN: Fkarin.wav?alt=media&token=7dd1a5ca-c9a6-4701-9154-df5640d25afc
  ZAWAZAWA: Fzawazawa.wav?alt=media&token=5e2568ff-5522-404c-858f-ff2331a35ef1
  MUSCLE: Fmuscle.wav?alt=media&token=dec0ade7-8c9e-4f5c-a485-1e99443b7e39
  NEKO: Fneko.wav?alt=media&token=47fda8c8-0c8b-4679-8ce4-029f242eac81
  NEKO_FULL: Fnekofull.wav?alt=media&token=7bf1567a-b41c-404d-a883-0da68219f942
  TABERUNGO: Ftaberungo.wav?alt=media&token=d75b4b09-4e1f-4323-9b9c-dd9de09cce78
  TABERUNGONOUTA: Ftaberungonouta.wav?alt=media&token=71d16c18-bd21-463e-b4e5-b0cbc1bd217c
  D4DJ: FD4DJ.wav?alt=media&token=ccb7fbfc-e2e4-4ddb-b797-f9b02bbf5ed7
  KNOCK_BRUSH: Fknock_brush.wav?alt=media&token=a7b54db4-f8d5-499f-9692-67a95316a9b8
  OGURAYUI: Fogurayui.wav?alt=media&token=d8d3d53f-2394-4d06-be48-643938cce2e9
  RESCUE: Frescue.wav?alt=media&token=940eb70c-13bd-48f5-8dc5-3877c64a97d7
  SYMPHOGEAR: Fsymphogear.wav?alt=media&token=2db2819c-c47d-439a-8f07-e84c5a2a6e63
